spring:
  application:
    name: first-db
  datasource:
    url: jdbc:h2:file:C:/Users/laabidi.raissi/work/mimo/data/first/countries
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  h2:
    console.enabled: true      

#http://localhost:8080/h2-console    